//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public int saleId { get; set; }
        public string productName { get; set; }
        public string clientName { get; set; }
        public Nullable<int> productUnitvalue { get; set; }
        public Nullable<int> saleTotalvalue { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<int> saleQuantity { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
